# Generated by Django 4.2 on 2024-05-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aio_bot', '0003_remove_botuser_photo_bayusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bayusers',
            old_name='tg_id',
            new_name='name',
        ),
    ]
