# Generated by Django 4.2 on 2024-05-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aio_bot', '0004_rename_tg_id_bayusers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bayusers',
            old_name='name',
            new_name='user',
        ),
    ]
