# Generated by Django 4.2 on 2024-05-02 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aio_bot', '0005_rename_name_bayusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aio_bot.botuser', verbose_name='Пользователь Telegram'),
        ),
    ]
